const products = [
    {
        id: 1,
        category: "Electronics",
        title: "Smartphone",
        price: 15000,
        stockAvailable: true,
    },
    {
        id: 2,
        category: "Electronics",
        title: "Bluetooth Speaker",
        price: 3500,
        stockAvailable: true,
    },
    {
        id: 3,
        category: "Electronics",
        title: "Wireless Mouse",
        price: 800,
        stockAvailable: true,
    },
    {
        id: 4,
        category: "Electronics",
        title: "Smart TV",
        price: 45000,
        stockAvailable: true,
    },
    {
        id: 5,
        category: "Electronics",
        title: "External Hard Drive",
        price: 6000,
        stockAvailable: true,
    },
    {
        id: 6,
        category: "Apparel",
        title: "Men's T-shirt",
        price: 500,
        stockAvailable: true,
    },
    {
        id: 7,
        category: "Apparel",
        title: "Women's Jeans",
        price: 1800,
        stockAvailable: true,
    },
    {
        id: 8,
        category: "Apparel",
        title: "Winter Jacket",
        price: 2500,
        stockAvailable: true,
    },
    {
        id: 9,
        category: "Apparel",
        title: "Running Shorts",
        price: 900,
        stockAvailable: true,
    },
    {
        id: 10,
        category: "Apparel",
        title: "Formal Shirt",
        price: 1200,
        stockAvailable: true,
    },
    {
        id: 11,
        category: "Home Goods",
        title: "Coffee Maker",
        price: 4000,
        stockAvailable: true,
    },
    {
        id: 12,
        category: "Home Goods",
        title: "Bedding Set",
        price: 3000,
        stockAvailable: true,
    },
    {
        id: 13,
        category: "Home Goods",
        title: "Cookware Set",
        price: 7500,
        stockAvailable: true,
    },
    {
        id: 14,
        category: "Home Goods",
        title: "LED Desk Lamp",
        price: 1100,
        stockAvailable: true,
    },
    {
        id: 15,
        category: "Home Goods",
        title: "Area Rug",
        price: 5000,
        stockAvailable: true,
    },
    {
        id: 16,
        category: "Books",
        title: "Science Fiction Novel",
        price: 450,
        stockAvailable: true,
    },
    {
        id: 17,
        category: "Books",
        title: "Cookbook",
        price: 850,
        stockAvailable: true,
    },
    {
        id: 18,
        category: "Books",
        title: "History Textbook",
        price: 1500,
        stockAvailable: true,
    },
    {
        id: 19,
        category: "Books",
        title: "Children's Storybook",
        price: 300,
        stockAvailable: true,
    },
    {
        id: 20,
        category: "Books",
        title: "Fantasy Series Part 1",
        price: 600,
        stockAvailable: true,
    },
    {
        id: 21,
        category: "Sports & Outdoors",
        title: "Yoga Mat",
        price: 1000,
        stockAvailable: true,
    },
    {
        id: 22,
        category: "Sports & Outdoors",
        title: "Dumbbell Set",
        price: 2500,
        stockAvailable: true,
    },
    {
        id: 23,
        category: "Sports & Outdoors",
        title: "Hiking Backpack",
        price: 3500,
        stockAvailable: true,
    },
    {
        id: 24,
        category: "Sports & Outdoors",
        title: "Water Bottle",
        price: 400,
        stockAvailable: true,
    },
    {
        id: 25,
        category: "Sports & Outdoors",
        title: "Trekking Poles",
        price: 1800,
        stockAvailable: true,
    },
    {
        id: 26,
        category: "Beauty & Health",
        title: "Face Moisturizer",
        price: 700,
        stockAvailable: true,
    },
    {
        id: 27,
        category: "Beauty & Health",
        title: "Shampoo",
        price: 300,
        stockAvailable: true,
    },
    {
        id: 28,
        category: "Beauty & Health",
        title: "Vitamin C Serum",
        price: 1200,
        stockAvailable: true,
    },
    {
        id: 29,
        category: "Beauty & Health",
        title: "Electric Toothbrush",
        price: 2000,
        stockAvailable: true,
    },
    {
        id: 30,
        category: "Beauty & Health",
        title: "Sunscreen SPF 50",
        price: 550,
        stockAvailable: true,
    }
];

module.exports = products;